apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-nodejs-app.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Set to "true" if you want an internal NLB
  labels:
    {{- include "my-nodejs-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer  # Change this to LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-nodejs-app.selectorLabels" . | nindent 4 }}
